### ISSUE TITLE
CSS-modules

### ISSUE THREAD

**Issue by sergiokopplin** [ueno-llc/starter-kit-universally#20]
Thanks for the good work here.

These configs are great! Are you planning to create a pr with those (react-universally)?
I can help you with the postcss branch

https://github.com/ueno-llc/starter-kit-universally/blob/master/internal/webpack/configFactory.js#L64

**Comment by birkir** [comment]
Hey Sergio, great having some interest in the project.

This starter kit is packed with much more features than react-universally, so it cannot be merged straight away. We have built features here that end up in react-universally for sure, but which ones depend on the project and it's community.

We have had css orientated branches in react-universally before, but we're scraping them for now.

**Comment by sergiokopplin** [comment]
Hmm ok, thanks for the reply!
Nice work here! Cheers!
