### ISSUE TITLE
Add a fork link back to upstream

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/starter-kit-universally#30]
The repo is currently accidentally a clone and not a fork. We should create a new repo as a fork!

**Comment by baldurh** [comment]
I believe the best way to achieve this is to do the following:
- Merge all outstanding pull requests
- Fork the upstream (https://github.com/ctrlplusb/react-universally)
- Force push all branches from this repo to the newly forked repo
- Delete this repo
- Rename the new repo
