### ISSUE TITLE
Wrong uppercase filename throw an error

### ISSUE THREAD

**Issue by jeremybarbet** [ueno-llc/starter-kit-universally#6]
Reproduction steps:

- Go to `routes` folder
- Open `about/index.js` file.
- Change import path to `export default from './about';`
- Build is stopped and throw the error below.

![screen shot 2017-03-16 at 13 16 41](https://cloud.githubusercontent.com/assets/937328/23997806/d2c8ad4c-0a4a-11e7-8298-c2c48155fd6d.png)

**Comment by osk** [comment]
Issue with webpack, fixed via [this PR](https://github.com/webpack/webpack/pull/4368) but hasn't been released. Until then, don't import files that don't exist 😆

**Comment by jeremybarbet** [comment]
Yeah, I just wanted to be sure, the starter kit is universally good :D

**Comment by osk** [comment]
Fixed with webpack 2.3!

**Comment by jeremybarbet** [comment]
YEAH! 🙏🏻
